// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1BHRVSyShMIPCFBtdDUNvP2CJk2eisU',
    appId: '1:622041731159:ios:6b5ac22d0b51d968205312',
    messagingSenderId: '622041731159',
    projectId: 'smart-trip-planner-mobile',
    storageBucket: 'smart-trip-planner-mobile.firebasestorage.app',
    iosClientId: '622041731159-ud1ip6e3otm397km1src7gdt9h73lpue.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1BHRVSyShMIPCFBtdDUNvP2CJk2eisU',
    appId: '1:622041731159:ios:6b5ac22d0b51d968205312',
    messagingSenderId: '622041731159',
    projectId: 'smart-trip-planner-mobile',
    storageBucket: 'smart-trip-planner-mobile.firebasestorage.app',
    iosClientId: '622041731159-ud1ip6e3otm397km1src7gdt9h73lpue.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTripPlanner',
  );
}
